### PR TITLE
add exercise 1 with c++

### PR DESCRIPTION
**Pull request by Shunsuke-Hori**
It should work with armadillo

I spent tons of time for the setup of armadillo in my Windows laptop

### CODE REVIEW

**Comment by Shunsuke-Hori** [comment]
hold on a second

**Comment by Shunsuke-Hori** [comment]
READY!!

**Comment by vikjam** [comment]
Success! On macOS, I just executed the following

```{bash}
$ brew install armadillo
$ clang++ exercise1.cpp -o exercise1 -DARMA_DONT_USE_WRAPPER -framework Accelerate
$ ./exercise1
Armadillo version: 8.300.4 (Tropical Shenanigans)
A:
   6.0000   9.0000   2.0000
   1.0000   8.0000   2.0000
  -3.0000   1.0000  -6.0000
B:
  -4.0000   7.0000  -7.0000
  -1.0000   6.0000  -5.0000
   2.0000  -5.0000  -1.0000
A * B:
  -29.0000   86.0000  -89.0000
   -8.0000   45.0000  -49.0000
   -1.0000   15.0000   22.0000

A^4:
   2.5630e+03   1.4142e+04   2.0460e+03
   9.1800e+02   6.4990e+03   7.8600e+02
  -1.2900e+02  -2.5470e+03   8.9200e+02

A' * B^(-1):
  -1.8333   3.0000   0.8333
  -3.8958   5.3750  -0.6042
  -0.4375   1.6250   0.9375

B.^3:
  -6.4000e+01   3.4300e+02  -3.4300e+02
  -1.0000e+00   2.1600e+02  -1.2500e+02
   8.0000e+00  -1.2500e+02  -1.0000e+00

A./B:
  -1.5000   1.2857  -0.2857
  -1.0000   1.3333  -0.4000
  -1.5000  -0.2000   6.0000

AB:
  -0.5920   0.0960  -0.2720
  -0.0400   0.5200  -0.6400
  -0.0440   0.8720   0.1960

Exercise d. (i.e. matrix C):
         0   18.0000         0
         0   16.0000         0
         0         0         0

Exercise 1e (1)
   13.0000   48.0000
   34.0000   40.0000

Exercise 1e (2)
   51.0000
   45.0000
   43.0000

Exercise 1e (3)
  -22.0000  -80.0000  -19.0000
```

**Review by vikjam — APPROVED** [review]
Looks good! Just renamed the file and escaped the \B (which threw a warning earlier for me).

**Comment by Shunsuke-Hori** [comment]
@vikjam thanks!! Feel free to merge this

PS: I finally figured out how to compile without VS

**Pull request merged**
